var inf = [
				{
				"src": "img/indexPicture/girl_img1.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img2.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img3.jpg",
				"num":"6.6",
				"name":"HAVVA全球同步春上新  冬爆款",
				"days":"剩4天"
				},
				{
				"src": "img/indexPicture/girl_img4.jpg",
				"num":"2.7",
				"name":"索菲斯尔SOFSIL特卖旗舰店",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img5.jpg",
				"num":"2.2",
				"name":"高梵羽绒大衣爆款精选专场",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img6.jpg",
				"num":"1.1",
				"name":"大衣&羊",
				"days":"剩2天"
				},
				{
				"src": "img/indexPicture/girl_img1.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img2.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img3.jpg",
				"num":"6.6",
				"name":"HAVVA全球同步春上新  冬爆款",
				"days":"剩4天"
				},
				{
				"src": "img/indexPicture/girl_img4.jpg",
				"num":"2.7",
				"name":"索菲斯尔SOFSIL特卖旗舰店",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img5.jpg",
				"num":"2.2",
				"name":"高梵羽绒大衣爆款精选专场",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img6.jpg",
				"num":"1.1",
				"name":"大衣&羊",
				"days":"剩2天"
				},
				{
				"src": "img/indexPicture/girl_img1.jpg",
				"num":"1.1",
				"name":"大衣&羊",
				"days":"剩2天"
				},
				{
				"src": "img/indexPicture/girl_img2.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img3.jpg",
				"num":"6.6",
				"name":"HAVVA全球同步春上新  冬爆款",
				"days":"剩4天"
				},
				{
				"src": "img/indexPicture/girl_img4.jpg",
				"num":"2.7",
				"name":"索菲斯尔SOFSIL特卖旗舰店",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img5.jpg",
				"num":"2.2",
				"name":"高梵羽绒大衣爆款精选专场",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img6.jpg",
				"num":"1.1",
				"name":"大衣&羊",
				"days":"剩2天"
				},
				{
				"src": "img/indexPicture/girl_img1.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img2.jpg",
				"num":"1.1",
				"name":"超级疯抢日 直击底价-玛玛MaxM...",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img3.jpg",
				"num":"6.6",
				"name":"HAVVA全球同步春上新  冬爆款",
				"days":"剩4天"
				},
				{
				"src": "img/indexPicture/girl_img4.jpg",
				"num":"2.7",
				"name":"索菲斯尔SOFSIL特卖旗舰店",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img5.jpg",
				"num":"2.2",
				"name":"高梵羽绒大衣爆款精选专场",
				"days":"剩3天"
				},
				{
				"src": "img/indexPicture/girl_img6.jpg",
				"num":"1.1",
				"name":"大衣&羊",
				"days":"剩2天"
				}
			]
//2*6
var shoe = [
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img1.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img2.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img3.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img4.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/shoe_img5.jpg",
				"num":"2.4",
				"name":"蝶愫tigrisso女鞋专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/shoe_img6.jpg",
				"num":"2.9",
				"name":"美式COACH包包专场",
				"days":"剩3天"
				}
			]
var boy =
			[
				{
				'src':"img/indexPicture/boy_img1.jpg",
				"num":"1",
				"name":"热销榜单-太子龙TEDELON男装",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img2.jpg",
				"num":"0.9",
				"name":"阿恩蓝托 ALT FINE INS男装爆款疯...",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img3.jpg",
				"num":"0.8",
				"name":"森马潮牌GLEMALL特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img4.jpg",
				"num":"0.8",
				"name":"百郡爵BALJUNJUE特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img5.jpg",
				"num":"1.4",
				"name":"阿仕顿特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img6.jpg",
				"num":"1",
				"name":"马克华菲男装特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img1.jpg",
				"num":"1",
				"name":"热销榜单-太子龙TEDELON男装",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img2.jpg",
				"num":"0.9",
				"name":"阿恩蓝托 ALT FINE INS男装爆款疯...",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img3.jpg",
				"num":"0.8",
				"name":"森马潮牌GLEMALL特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img4.jpg",
				"num":"0.8",
				"name":"百郡爵BALJUNJUE特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img5.jpg",
				"num":"1.4",
				"name":"阿仕顿特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img6.jpg",
				"num":"1",
				"name":"马克华菲男装特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img1.jpg",
				"num":"1",
				"name":"热销榜单-太子龙TEDELON男装",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img2.jpg",
				"num":"0.9",
				"name":"阿恩蓝托 ALT FINE INS男装爆款疯...",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img3.jpg",
				"num":"0.8",
				"name":"森马潮牌GLEMALL特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img4.jpg",
				"num":"0.8",
				"name":"百郡爵BALJUNJUE特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img5.jpg",
				"num":"1.4",
				"name":"阿仕顿特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img6.jpg",
				"num":"1",
				"name":"马克华菲男装特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img1.jpg",
				"num":"1",
				"name":"热销榜单-太子龙TEDELON男装",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img2.jpg",
				"num":"0.9",
				"name":"阿恩蓝托 ALT FINE INS男装爆款疯...",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img3.jpg",
				"num":"0.8",
				"name":"森马潮牌GLEMALL特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img4.jpg",
				"num":"0.8",
				"name":"百郡爵BALJUNJUE特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img5.jpg",
				"num":"1.4",
				"name":"阿仕顿特卖旗舰店",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/boy_img6.jpg",
				"num":"1",
				"name":"马克华菲男装特卖旗舰店",
				"days":"剩3天"
				}
			]
var sport =
			[
				{
				'src':"img/indexPicture/sport_img1.jpg",
				"num":"1.5",
				"name":"耐克Nike运动鞋特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img2.jpg",
				"num":"1.6",
				"name":"adidas运动男女混合专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/sport_img3.jpg",
				"num":"1.4",
				"name":"彪马PUMA男女鞋服特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img4.jpg",
				"num":"5.7",
				"name":"匡威converse潮流运动专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img5.jpg",
				"num":"1.2",
				"name":"samyama女款健美服饰专场",
				"days":"剩9天"
				},
				{
				'src':"img/indexPicture/sport_img6.jpg",
				"num":"2.7",
				"name":"ONISUKATIGER复古休闲鞋专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img1.jpg",
				"num":"1.5",
				"name":"耐克Nike运动鞋特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img2.jpg",
				"num":"1.6",
				"name":"adidas运动男女混合专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/sport_img3.jpg",
				"num":"1.4",
				"name":"彪马PUMA男女鞋服特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img4.jpg",
				"num":"5.7",
				"name":"匡威converse潮流运动专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img5.jpg",
				"num":"1.2",
				"name":"samyama女款健美服饰专场",
				"days":"剩9天"
				},
				{
				'src':"img/indexPicture/sport_img6.jpg",
				"num":"2.7",
				"name":"ONISUKATIGER复古休闲鞋专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img1.jpg",
				"num":"1.5",
				"name":"耐克Nike运动鞋特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img2.jpg",
				"num":"1.6",
				"name":"adidas运动男女混合专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/sport_img3.jpg",
				"num":"1.4",
				"name":"彪马PUMA男女鞋服特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img4.jpg",
				"num":"5.7",
				"name":"匡威converse潮流运动专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img5.jpg",
				"num":"1.2",
				"name":"samyama女款健美服饰专场",
				"days":"剩9天"
				},
				{
				'src':"img/indexPicture/sport_img6.jpg",
				"num":"2.7",
				"name":"ONISUKATIGER复古休闲鞋专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img1.jpg",
				"num":"1.5",
				"name":"耐克Nike运动鞋特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img2.jpg",
				"num":"1.6",
				"name":"adidas运动男女混合专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/sport_img3.jpg",
				"num":"1.4",
				"name":"彪马PUMA男女鞋服特卖专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img4.jpg",
				"num":"5.7",
				"name":"匡威converse潮流运动专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/sport_img5.jpg",
				"num":"1.2",
				"name":"samyama女款健美服饰专场",
				"days":"剩9天"
				},
				{
				'src':"img/indexPicture/sport_img6.jpg",
				"num":"2.7",
				"name":"ONISUKATIGER复古休闲鞋专场",
				"days":"剩3天"
				}
			]

var omament =
			[
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img1.jpg",
				"num":"7.2",
				"name":"周大福珠宝门店专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/omament_img2.jpg",
				"num":"1.1",
				"name":"Vomdir围巾打底裤直降专场",
				"days":"剩5天"
				},
				{
				'src':"img/indexPicture/omament_img3.jpg",
				"num":"1.9",
				"name":"依波EBOHR手表-限时闪降专场",
				"days":"剩20时"
				},
				{
				'src':"img/indexPicture/omament_img4.jpg",
				"num":"1.3",
				"name":"佰色传情BRI.R精品专场",
				"days":"剩2天"
				},
				{
				'src':"img/indexPicture/omament_img5.jpg",
				"num":"1.5",
				"name":"尚都比拉配饰限时闪降专场",
				"days":"剩6天"
				},
				{
				'src':"img/indexPicture/omament_img6.jpg",
				"num":"1.2",
				"name":"施华洛世奇 眼镜专场",
				"days":"剩3天"
				}
			]						

var beauty = 
			[
				{
				'src':"img/indexPicture/beauty_img1.jpg",
				"num":"1.6",
				"name":"韩国高端美容院线AHC专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img2.jpg",
				"num":"1.5",
				"name":"高姿COGI化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img3.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img4.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img5.jpg",
				"num":"2.2",
				"name":"玛丽黛佳MarieDalgar彩妆专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img6.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img1.jpg",
				"num":"1.6",
				"name":"韩国高端美容院线AHC专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img2.jpg",
				"num":"1.5",
				"name":"高姿COGI化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img3.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img4.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img5.jpg",
				"num":"2.2",
				"name":"玛丽黛佳MarieDalgar彩妆专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img6.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img1.jpg",
				"num":"1.6",
				"name":"韩国高端美容院线AHC专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img2.jpg",
				"num":"1.5",
				"name":"高姿COGI化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img3.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img4.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img5.jpg",
				"num":"2.2",
				"name":"玛丽黛佳MarieDalgar彩妆专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img6.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img1.jpg",
				"num":"1.6",
				"name":"韩国高端美容院线AHC专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img2.jpg",
				"num":"1.5",
				"name":"高姿COGI化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img3.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img4.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img5.jpg",
				"num":"2.2",
				"name":"玛丽黛佳MarieDalgar彩妆专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img6.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img1.jpg",
				"num":"1.6",
				"name":"韩国高端美容院线AHC专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img2.jpg",
				"num":"1.5",
				"name":"高姿COGI化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img3.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img4.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img5.jpg",
				"num":"2.2",
				"name":"玛丽黛佳MarieDalgar彩妆专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/beauty_img6.jpg",
				"num":"3.6",
				"name":"阿芙AFU精油护肤专场",
				"days":"剩3天"	
				}
			]

var baby = 
			[
				{
				'src':"img/indexPicture/baby_img1.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img2.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img3.jpg",
				"num":"1.2",
				"name":"子初特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img4.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img5.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img6.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img1.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img2.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img3.jpg",
				"num":"1.2",
				"name":"子初特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img4.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img5.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img6.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img1.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img2.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img3.jpg",
				"num":"1.2",
				"name":"子初特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img4.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img5.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img6.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img1.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img2.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img3.jpg",
				"num":"1.2",
				"name":"子初特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img4.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img5.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img6.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img1.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img2.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img3.jpg",
				"num":"1.2",
				"name":"子初特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img4.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/baby_img5.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/baby_img6.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				}
			]

var home = 
			[
				{
				'src':"img/indexPicture/home_img1.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img2.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img3.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img4.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img5.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img6.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},	
				{
				'src':"img/indexPicture/home_img1.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img2.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img3.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img4.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img5.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img6.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img1.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img2.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img3.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img4.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img5.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img6.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img1.jpg",
				"num":"1.6",
				"name":"贝贝怡Bornbay特卖旗舰店",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img2.jpg",
				"num":"1.8",
				"name":"木木mumutu童鞋特卖旗舰店.",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img3.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img4.jpg",
				"num":"1.6",
				"name":"限时闪将-衣品天成EPTISON男女童...",
				"days":"剩19天"	
				},
				{
				'src':"img/indexPicture/home_img5.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/home_img6.jpg",
				"num":"3.1",
				"name":"薇诺娜winona化妆品专场",
				"days":"剩3天"	
				}
			]
var nation = 
			[
				{
				'src':"img/indexPicture/national_img1.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img2.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img3.jpg",
				"num":"3.1",
				"name":"欧洲品质生活膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img4.jpg",
				"num":"2.8",
				"name":"美国Schiff维骨力保健营养专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img5.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img6.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img1.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img2.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img3.jpg",
				"num":"3.1",
				"name":"欧洲品质生活膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img4.jpg",
				"num":"2.8",
				"name":"美国Schiff维骨力保健营养专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img5.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img6.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img1.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img2.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img3.jpg",
				"num":"3.1",
				"name":"欧洲品质生活膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img4.jpg",
				"num":"2.8",
				"name":"美国Schiff维骨力保健营养专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img5.jpg",
				"num":"3.1",
				"name":"澳洲Swisse天然营养膳食专场",
				"days":"剩3天"
				},
				{
				'src':"img/indexPicture/national_img6.jpg",
				"num":"5.6",
				"name":"亚洲国际大奖美颜纤体专场",
				"days":"剩3天"
				}
			]

var life = 
			[
				{
				'src':"img/indexPicture/life_img1.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img2.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				},
				{
				'src':"img/indexPicture/life_img3.jpg",
				"num":"2.5",
				"name":"东阿胶阿胶养颜专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img4.jpg",
				"num":"5.5",
				"name":"意大利费罗列Ferrero Rocher巧克力...",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img5.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img6.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				},
				{
				'src':"img/indexPicture/life_img1.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img2.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				},
				{
				'src':"img/indexPicture/life_img3.jpg",
				"num":"2.5",
				"name":"东阿胶阿胶养颜专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img4.jpg",
				"num":"5.5",
				"name":"意大利费罗列Ferrero Rocher巧克力...",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img5.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img6.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				},
				{
				'src':"img/indexPicture/life_img1.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img2.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				},
				{
				'src':"img/indexPicture/life_img3.jpg",
				"num":"2.5",
				"name":"东阿胶阿胶养颜专场",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img4.jpg",
				"num":"5.5",
				"name":"意大利费罗列Ferrero Rocher巧克力...",
				"days":"剩3天"	
				},
				{
				'src':"img/indexPicture/life_img5.jpg",
				"num":"2.3",
				"name":"汤臣倍保健品专场",
				"days":"剩2天"	
				},
				{
				'src':"img/indexPicture/life_img6.jpg",
				"num":"3",
				"name":"乐奈美味休闲零食专场",
				"days":"剩6天"	
				}
				
			]

var advance = 
			[
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img1.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img2.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img3.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				},
				{
				'src':"img/indexPicture/advance_img4.jpg",
				'advanceName':'戴维贝拉DAVE&BELLA婴幼女...',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img5.jpg",
				'advanceName':'1.12唯品快抢-冰雪黑锋',
				'discountNum':'2.8'
				},
				{
				'src':"img/indexPicture/advance_img6.jpg",
				'advanceName':'1.12今年秒杀',
				'discountNum':'1.3'
				}
			]
